import React from "react";
import { ChartBlock } from "../components/runtime/ChartBlock";
import { TableBlock } from "../components/runtime/TableBlock";
import { MetricCardBlock } from "../components/runtime/MetricCardBlock";

const Racun: React.FC = () => {
  return (
    <div id="page-racun-6">
    <div id="ixllyl" style={{"display": "flex", "height": "100vh", "fontFamily": "Arial, sans-serif", "--chart-color-palette": "default"}}>
      <nav id="i6igx4" style={{"width": "250px", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "padding": "20px", "overflowY": "auto", "display": "flex", "flexDirection": "column", "--chart-color-palette": "default"}}>
        <h2 id="ivrjcg" style={{"marginTop": "0", "fontSize": "24px", "marginBottom": "30px", "fontWeight": "bold", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <div id="iqhkus" style={{"display": "flex", "flexDirection": "column", "flex": "1", "--chart-color-palette": "default"}}>
          <a id="ic1r7o" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/klijent">{"Klijent"}</a>
          <a id="iw6c8u" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/destinacija">{"Destinacija"}</a>
          <a id="iufp9e" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/hotel">{"Hotel"}</a>
          <a id="i1s8ah" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/aranzman">{"Aranzman"}</a>
          <a id="iy8x0j" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/rezervacija">{"Rezervacija"}</a>
          <a id="iqflhg" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/vodic">{"Vodic"}</a>
          <a id="ifd3k9" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "rgba(255,255,255,0.2)", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/racun">{"Racun"}</a>
        </div>
        <p id="i2vv9s" style={{"marginTop": "auto", "paddingTop": "20px", "borderTop": "1px solid rgba(255,255,255,0.2)", "fontSize": "11px", "opacity": "0.8", "textAlign": "center", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="ia1g08" style={{"flex": "1", "padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default"}}>
        <h1 id="i0ax0u" style={{"marginTop": "0", "color": "#333", "fontSize": "32px", "marginBottom": "10px", "--chart-color-palette": "default"}}>{"Racun"}</h1>
        <p id="il8g1e" style={{"color": "#666", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"Manage Racun data"}</p>
        <TableBlock id="table-racun-6" styles={{"width": "auto", "height": "auto", "padding": "0", "margin": "0", "position": "static", "textAlign": "left", "zIndex": 0, "backgroundColor": "#2c3e50", "--chart-color-palette": "default"}} title="Racun List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "BrojRacuna", "column_type": "field", "field": "brojRacuna", "type": "str", "required": true}, {"label": "DatumIzdavanja", "column_type": "field", "field": "datumIzdavanja", "type": "date", "required": true}, {"label": "DatumDospeca", "column_type": "field", "field": "datumDospeca", "type": "date", "required": true}, {"label": "Iznos", "column_type": "field", "field": "iznos", "type": "float", "required": true}, {"label": "Pdv", "column_type": "field", "field": "pdv", "type": "float", "required": true}, {"label": "Ukupno", "column_type": "field", "field": "ukupno", "type": "float", "required": true}, {"label": "Nacin Placanja", "column_type": "field", "field": "nacin_placanja", "type": "enum", "options": ["GOTOVINA", "KARTICA", "ONLINE", "PRENOS"], "required": true}, {"label": "Status", "column_type": "field", "field": "status", "type": "enum", "options": ["IZDAT", "KASNI", "OTKAZAN", "PLACEN"], "required": true}], "formColumns": [{"column_type": "field", "field": "brojRacuna", "label": "brojRacuna", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "datumIzdavanja", "label": "datumIzdavanja", "type": "date", "required": true, "defaultValue": null}, {"column_type": "field", "field": "datumDospeca", "label": "datumDospeca", "type": "date", "required": true, "defaultValue": null}, {"column_type": "field", "field": "iznos", "label": "iznos", "type": "float", "required": true, "defaultValue": null}, {"column_type": "field", "field": "pdv", "label": "pdv", "type": "float", "required": true, "defaultValue": null}, {"column_type": "field", "field": "ukupno", "label": "ukupno", "type": "float", "required": true, "defaultValue": null}, {"column_type": "field", "field": "nacin_placanja", "label": "nacin_placanja", "type": "enum", "required": true, "defaultValue": null, "options": ["GOTOVINA", "KARTICA", "ONLINE", "PRENOS"]}, {"column_type": "field", "field": "status", "label": "status", "type": "enum", "required": true, "defaultValue": null, "options": ["IZDAT", "KASNI", "OTKAZAN", "PLACEN"]}, {"column_type": "lookup", "path": "klijent_1", "field": "klijent_1", "lookup_field": "ime", "entity": "Klijent", "type": "str", "required": true}, {"column_type": "lookup", "path": "aranzman_4", "field": "aranzman_4", "lookup_field": "naziv", "entity": "Aranzman", "type": "str", "required": true}]}} dataBinding={{"entity": "Racun", "endpoint": "/racun/"}} />
        <div id="ia20le" className="gjs-row" style={{"height": "276px", "--chart-color-palette": "default", "display": "flex", "paddingTop": "10px", "paddingRight": "10px", "paddingBottom": "10px", "paddingLeft": "10px", "width": "100%", "flexWrap": "wrap"}}>
          <div id="i8jkm3" className="gjs-cell" style={{"height": "auto", "padding": "0", "margin": "0", "position": "static", "textAlign": "left", "zIndex": 0, "--chart-color-palette": "default", "flex": "1 1 calc(33.333% - 20px)", "minWidth": "250px"}}>
            <div id="izpd5w" style={{"padding": "20px", "backgroundColor": "#4b3c82", "--chart-color-palette": "default"}}>
              <div id="ipqdmb" style={{"maxWidth": "1400px", "margin": "0 auto", "--chart-color-palette": "default"}}>
                <div id="in1nja" style={{"marginBottom": "30px"}}>
                  <h1 id="ikyahe" style={{"color": "white", "margin": "0 0 10px 0", "fontSize": "32px", "--chart-color-palette": "default"}}>{"Analytics Dashboard"}</h1>
                  <p id="i3evvc" style={{"color": "rgba(255,255,255,0.8)", "margin": "0", "--chart-color-palette": "default"}}>{"Real-time insights and metrics"}</p>
                </div>
                <div id="ifu63l" className="kpi-row" style={{"display": "grid", "gridTemplateColumns": "repeat(auto-fit, minmax(250px, 1fr))", "gap": "20px", "marginBottom": "30px", "--chart-color-palette": "default"}}>
                  <MetricCardBlock id="i4dfzj" styles={{"width": "100%", "minHeight": "140px", "--chart-color-palette": "default"}} metric={{"metricTitle": "Hoteli", "format": "number", "valueColor": "#2c3e50", "valueSize": 32, "showTrend": true, "positiveColor": "#27ae60", "negativeColor": "#e74c3c", "value": 0, "trend": 12}} dataBinding={{"entity": "Hotel", "endpoint": "/hotel/", "data_field": "naziv"}} />
                  <MetricCardBlock id="ikmpe7" styles={{"width": "100%", "minHeight": "140px", "--chart-color-palette": "default"}} metric={{"metricTitle": "Destinacije", "format": "number", "valueColor": "#2c3e50", "valueSize": 32, "showTrend": true, "positiveColor": "#27ae60", "negativeColor": "#e74c3c", "value": 0, "trend": 12}} dataBinding={{"entity": "Destinacija", "endpoint": "/destinacija/", "data_field": "zemlja"}} />
                  <MetricCardBlock id="ip04w5" styles={{"width": "100%", "minHeight": "140px", "--chart-color-palette": "default"}} metric={{"metricTitle": "Klijenti", "format": "number", "valueColor": "#2c3e50", "valueSize": 32, "showTrend": true, "positiveColor": "#27ae60", "negativeColor": "#e74c3c", "value": 0, "trend": 12}} dataBinding={{"entity": "Klijent", "endpoint": "/klijent/", "data_field": "Rezervacija"}} />
                  <MetricCardBlock id="ijjbuf" styles={{"width": "100%", "minHeight": "140px", "--chart-color-palette": "default"}} metric={{"metricTitle": "Vodici", "format": "number", "valueColor": "#2c3e50", "valueSize": 32, "showTrend": true, "positiveColor": "#27ae60", "negativeColor": "#e74c3c", "value": 0, "trend": 12}} dataBinding={{"entity": "Vodic", "endpoint": "/vodic/", "data_field": "ime"}} />
                </div>
                <div id="iqea9l" className="charts-row" style={{"display": "grid", "gridTemplateColumns": "repeat(auto-fit, minmax(500px, 1fr))", "gap": "20px", "marginBottom": "20px", "--chart-color-palette": "default"}}>
                  <div id="i3s93a" style={{"background": "white", "padding": "25px", "borderRadius": "10px", "boxShadow": "0 4px 6px rgba(0,0,0,0.1)", "--chart-color-palette": "default"}}>
                    <h3 id="il68ca" style={{"margin": "0 0 20px 0", "color": "#2c3e50", "--chart-color-palette": "default"}}>{"Revenue Trend"}</h3>
                    <ChartBlock id="irc0zr" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} chartType="bar-chart" title="Bar Chart Title" color="#3498db" chart={{"barWidth": 30, "orientation": "vertical", "showGrid": true, "showLegend": true, "showTooltip": true, "stacked": false, "animate": true, "legendPosition": "top", "gridColor": "#e0e0e0", "barGap": 4}} series={[{"name": "Series_1", "label": "Series 1", "color": "#3498db"}]} />
                    <ChartBlock id="i4ik2u" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} chartType="line-chart" title="Line Chart Title" color="#4CAF50" chart={{"lineWidth": 2, "curveType": "monotone", "showGrid": true, "showLegend": true, "showTooltip": true, "animate": true, "legendPosition": "top", "gridColor": "#e0e0e0", "dotSize": 5}} series={[{"name": "Series_1", "label": "Series 1", "color": "#4CAF50"}]} />
                  </div>
                  <div id="i8pks8" style={{"background": "white", "padding": "25px", "borderRadius": "10px", "boxShadow": "0 4px 6px rgba(0,0,0,0.1)", "--chart-color-palette": "default"}}>
                    <h3 id="im6r4j" style={{"margin": "0 0 20px 0", "color": "#2c3e50", "--chart-color-palette": "default"}}>{"Category Distribution"}</h3>
                    <ChartBlock id="ija5jj" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} chartType="pie-chart" title="Pie Chart Title" color="default" chart={{"showLegend": true, "legendPosition": "bottom", "showLabels": true, "labelPosition": "inside", "paddingAngle": 0, "innerRadius": 0, "outerRadius": 80, "startAngle": 0, "endAngle": 360}} series={[{"name": "Series_1", "label": "Series 1", "color": "#4CAF50"}]} />
                    <ChartBlock id="ilk61j" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} chartType="radial-bar-chart" title="Radial Bar Chart Title" color="default" chart={{"startAngle": 90, "endAngle": 450, "innerRadius": 30, "outerRadius": 80, "showLegend": true, "legendPosition": "top", "showTooltip": true}} series={[{"name": "Series_1", "label": "Series 1", "color": "#4CAF50"}]} />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>    </div>
  );
};

export default Racun;
